[startup.cache]
name = "core.system"
after = ["udevtrigger"] #udevtrigger service is defined by the 0-initramfs
running_delay = -1

[startup.cache.args]
name = "/bin/sh"
args = ["-c", "/usr/bin/ensurecache.sh"]
