[main]
max_jobs = 524288
include = ["/etc/g8os/conf"]
log_level = "info"
network = "/etc/g8os/network.toml"

[containers]
max_count = 1000

[logging.file]
levels = [2, 4, 7, 8, 9]

[logging.ledis]
levels = [1, 2, 4, 7, 8, 9]
size = 10000 # how many log lines to keep in ledis

[stats]
enabled = true

[globals]
storage = ""
